version: "3.8"
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: kenji
      POSTGRES_PASSWORD: password
      POSTGRES_DB: t3db
    restart: always
    networks:
      - lesson
networks:
  lesson:
